function [ w, f, output ] = pns( obj, pen, x, theta, m, method)
% a wrapper that can be easily modified to change 
% parameters passed in
tfocs_opts = struct(...
    'alg'        , 'GRA' ,...
    'maxIts'     , 500   ,...
    'printEvery' , 0     ,...
    'restart'    , 100   ...
    );

options = struct(...
      'debug'          , 0          ,... % debug mode 
      'desc_param'     , 0.0001     ,... % sufficient descent parameter
      'display'        , 1         ,... % display frequency (<= 0 for no display) 
      'max_fun_evals'  , 5000       ,... % max number of function evaluations
      'max_iter'       , 100        ,... % max number of iterations
      'subprob_solver' , 'tfocs'    ,... % solver for solving subproblems
      'tfocs_opts'     , tfocs_opts ,... % subproblem solver options
      'ftol'           , 1e-7       ,... % stopping tolerance on relative change in the objective function 
      'optim_tol'      , 0       ,... % stopping tolerance on optimality condition
      'xtol'           , 1e-9       ,... % stopping tolerance on solution
      'sketch_dim'     , m         ,...
      'theta'          , theta       ,...
      'beta'           , 0.1        ,...
      'delta'          , 0.2      ,...
      'backtrack'      , 1           ,...
      'exact_stopping' , 0          ,...
      'downsample'     , 0           ,...
      'method'         , method    ...
      );
  
  [ w, f, output ] = pnsopt_pqn( obj, pen, x, options);
